flags: {}
packages:
- '.'
- location:
    git: https://github.com/positiondev/larceny
    commit: abc8dfb81a744fede701a3ebf6b334d881830292
  extra-dep: true
extra-deps:
- aeson-0.11.2.0
- atom-basic-0.2.4
- bytestring-builder-0.10.8.1.0
- directory-1.2.6.3
- dotenv-0.3.0.2
- fast-logger-2.4.6
- fn-0.3.0.1
- tagged-0.8.5
- transformers-compat-0.5.1.4
- html-entities-1.1.3
- megaparsec-5.0.0
- wai-3.2.1.1
- wai-extra-3.0.15.2
resolver: lts-5.14
