flags: {}
packages:
- '.'
- location: ../larceny
  extra-dep: true
- location: ../hspec-fn
  extra-dep: true
extra-deps:
- aeson-0.11.2.0
- bytestring-builder-0.10.8.1.0
- cereal-text-0.1.0.2
- digestive-functors-heist-0.8.6.2
- directory-1.2.6.3
- dotenv-0.3.0.2
- fast-logger-2.4.6
- fn-0.3.0.1
- http2-1.6.0
- logging-3.0.4
- megaparsec-5.0.0
- postgresql-simple-0.5.2.1
- wai-3.2.1.1
- wai-extra-3.0.15.2
- wai-session-clientsession-0.1
- warp-3.2.6
resolver: lts-5.14
