flags: {}
packages:
- '.'
extra-deps:
 - html-entities-1.1.4
 - logging-3.0.4
 - git: https://github.com/positiondev/fn
   commit: a57e55c177e135db8097517fc81081274ad2d5c0
   subdirs:
    - fn
    - fn-extra
 - git: https://github.com/positiondev/larceny
   commit: 05286ad4a66b61a363af32b1455145eb4160046c
resolver: lts-8.15
