flags: {}
packages:
- '.'
- location:
    git: https://github.com/positiondev/larceny
    commit: 8837d1bd092271046b4e7234b53f32dbcd04f900
  extra-dep: true
extra-deps: 
 - html-entities-1.1.4
resolver: lts-8.15
